[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "nanobrain"
description = "nanobrain"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "braceexpand",
    "datasets",
    "einops",
    "flash-attn-3",
    "flask",
    "fsspec",
    "huggingface-hub",
    "jaxtyping",
    "matplotlib",
    "nibabel",
    "numpy",
    "nvidia-ml-py",
    "omegaconf",
    "pandas",
    "pyyaml",
    "s3fs",
    "scikit-image",
    "scikit-learn",
    "scipy",
    "synthseg",
    "tabulate",
    "templateflow",
    "timm",
    "torch==2.14.0",
    "torchvision",
    "tqdm",
    "wandb",
    "webdataset",
    "zstandard",
]

[dependency-groups]
dev = [
    "ipython",
    "jupyter",
    "matplotlib",
    "pre-commit",
    "pytest",
    "python-dotenv",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
ignore = ["F722"]

[tool.uv.sources]
torch = { index = "pytorch-cu130" }
torchvision = { index = "pytorch-cu130" }
flash-attn-3 = { index = "pytorch-cu130" }
synthseg = { git = "https://github.com/MedARC-AI/SynthSeg.git", rev = "2690d9ac9ae28323d03043406cd21db0a8741547" }

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true
